/**
 * skill-icon.data.ts
 *
 * Maps skill IDs to game-icons SVG asset paths.
 * Generated by scripts/extract-icons.mjs from @iconify-json/game-icons.
 *
 * Update process:
 *   1. Edit SKILL_ICON_MAP in scripts/extract-icons.mjs
 *   2. Run: node scripts/extract-icons.mjs
 *   3. Update this file to match the new mapping
 */
export const SKILL_ICON_SRC: Readonly<Record<string, string>> = {
  // ── Utility ──────────────────────────────────────────────────────────
  'hydrate':        'assets/icons/water-drop.svg',
  'deep-focus':     'assets/icons/brain.svg',
  'log-day':        'assets/icons/open-book.svg',

  // ── Red Team ─────────────────────────────────────────────────────────
  'rt-xss':         'assets/icons/fire-bomb.svg',
  'rt-sqli':        'assets/icons/daggers.svg',
  'rt-idor':        'assets/icons/key.svg',
  'rt-csrf':        'assets/icons/fishing-hook.svg',
  'rt-path':        'assets/icons/locked-door.svg',
  'rt-ssrf':        'assets/icons/spider-web.svg',
  'rt-cmdi':        'assets/icons/lightning-frequency.svg',
  'rt-xxe':         'assets/icons/scroll-unfurled.svg',
  'rt-auth':        'assets/icons/combination-lock.svg',
  'rt-jwt':         'assets/icons/padlock.svg',
  'rt-upload':      'assets/icons/cloud-upload.svg',
  'rt-bizlogic':    'assets/icons/puzzle.svg',
  'rt-privesc':     'assets/icons/star-key.svg',

  // ── MMA ──────────────────────────────────────────────────────────────
  'mma-jab':        'assets/icons/punch.svg',
  'mma-cross':      'assets/icons/fulguro-punch.svg',
  'mma-hook':       'assets/icons/hook.svg',
  'mma-uppercut':   'assets/icons/punch-blast.svg',
  'mma-bodyhook':   'assets/icons/boxing-glove.svg',
  'mma-elbow':      'assets/icons/forearm.svg',
  'mma-kick':       'assets/icons/high-kick.svg',
  'mma-knee':       'assets/icons/boot-kick.svg',
  'mma-sltd':       'assets/icons/body-balance.svg',
  'mma-dltd':       'assets/icons/weight-lifting-down.svg',
  'mma-rnc':        'assets/icons/locked-chest.svg',
  'mma-guillotine': 'assets/icons/hook-swords.svg',
  'mma-kimura':     'assets/icons/arm-sling.svg',
  'mma-armbar':     'assets/icons/arm.svg',
  'mma-triangle':   'assets/icons/trident-shield.svg',

  // ── Strength ─────────────────────────────────────────────────────────
  'str-bench':      'assets/icons/weight-lifting-up.svg',
  'str-incbench':   'assets/icons/weight-lifting-up.svg',
  'str-deadlift':   'assets/icons/weight.svg',
  'str-rdl':        'assets/icons/weight-lifting-down.svg',
  'str-squat':      'assets/icons/armor-cuisses.svg',
  'str-pullup':     'assets/icons/daemon-pull.svg',
  'str-row':        'assets/icons/gear-stick.svg',
  'str-ohp':        'assets/icons/weight-lifting-up.svg',
  'str-curl':       'assets/icons/arm.svg',
  'str-tripdwn':    'assets/icons/weight-crush.svg',
  'str-latpd':      'assets/icons/armor-downgrade.svg',
  'str-cablerow':   'assets/icons/gear-stick-pattern.svg',
  'str-hipt':       'assets/icons/armor-cuisses.svg',
  'str-facepull':   'assets/icons/armor-punch.svg',
  'str-dip':        'assets/icons/weight-lifting-down.svg',

  // ── Swimming ─────────────────────────────────────────────────────────
  'sw-float':       'assets/icons/water-bottle.svg',
  'sw-seal':        'assets/icons/wave-strike.svg',
  'sw-free':        'assets/icons/water-splash.svg',
  'sw-back':        'assets/icons/wave-crest.svg',
  'sw-breast':      'assets/icons/water-polo.svg',
  'sw-butterfly':   'assets/icons/big-wave.svg',
  'sw-flip':        'assets/icons/whirlpool-shuriken.svg',
  'sw-stream':      'assets/icons/water-mill.svg',
  'sw-tread':       'assets/icons/waves.svg',

  // ── Guitar ───────────────────────────────────────────────────────────
  'gt-openchords':  'assets/icons/musical-notes.svg',
  'gt-power':       'assets/icons/guitar.svg',
  'gt-strum':       'assets/icons/guitar-bass-head.svg',
  'gt-penta':       'assets/icons/musical-score.svg',
  'gt-major':       'assets/icons/music-spell.svg',
  'gt-minor':       'assets/icons/musical-notes.svg',
  'gt-barre':       'assets/icons/guitar-head.svg',
  'gt-finger':      'assets/icons/piano-keys.svg',
  'gt-1645':        'assets/icons/musical-keyboard.svg',
  'gt-blues':       'assets/icons/bassoon.svg',
  'gt-hammer':      'assets/icons/claw-hammer.svg',
  'gt-dorian':      'assets/icons/music-spell.svg',
  'gt-vibrato':     'assets/icons/sound-waves.svg',

  // ── Coding ───────────────────────────────────────────────────────────
  'dev-feat':       'assets/icons/circuitry.svg',
  'dev-debug':      'assets/icons/cyber-eye.svg',
  'dev-arch':       'assets/icons/gears.svg',
  'dev-review':     'assets/icons/brain-dump.svg',
  'dev-learn':      'assets/icons/book-cover.svg',
  'dev-meeting':    'assets/icons/microchip.svg',

  // ── Sage ─────────────────────────────────────────────────────────────
  'sage-prayer':    'assets/icons/enlightenment.svg',
  'sage-bible':     'assets/icons/book-aura.svg',
  'sage-sermon':    'assets/icons/spell-book.svg',
  'sage-warfare':   'assets/icons/crossed-swords.svg',
};
